basePath: /api/v1
host: localhost:8081
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a simple rest api for category
  title: User API documentation
  version: 1.0.0
paths: {}
swagger: "2.0"
